name: Brian Boughton
markdown: redcarpet
pygments: true
permalink: /posts/:title
exclude: ['Rakefile']

url: http://brianboughton.com
description: A fantastic blog that is fantastic.
github: bboughton
twitter: brianboughton
linkedin: brianboughton
gravatar_url: http://gravatar.com/avatar/297a9ec71ee7721be5b0bda1b56090a4
